# /etc/skel/.bashrc

# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

alias vim="$HOME/.bin/nvim"
alias nvim="$HOME/.bin/nvim"

PATH=$PATH:$HOME/.bin
PATH=$PATH:$HOME/go/bin
PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools

# Binds 
bind '"\C-f": "sessionizer\n"'
